### PR TITLE
Prettify DetectAll recognizerOutputs slice

### PR DESCRIPTION
**Pull request by moredure**

### CODE REVIEW

**Comment by unknwon** [comment]
Thanks for the PR!

Could you justify the change?

**Comment by moredure** [comment]
Hi @unknwon , what do you mean about justify?

**Comment by unknwon** [comment]
In other words, why changes in the PR is needed, or what benefits of making these changes?

**Comment by moredure** [comment]
One data type convertion less

**Review by unknwon — APPROVED** [review]

**Pull request merged**
